import React from 'react';
import { AppPrivacyDocument, MailLink, PolicySection, PolicyThirdParty } from '../components/AppPrivacyDocument';

const sections: PolicySection[] = [
  {
    title: 'Information We Collect',
    subsections: [
      {
        title: 'A. Information That Stays on Your Device',
        intro: 'Yemini API Tester has no account system. Everything you create in the App is stored only on your device:',
        bullets: [
          { lead: 'Requests & Collections', text: 'URLs, HTTP methods, headers, query parameters, request bodies, tests, and the collections you organize them in.' },
          { lead: 'Credentials You Enter', text: 'API keys, bearer tokens, and basic-auth usernames and passwords that you type into a request.' },
          { lead: 'Request History', text: 'A log of the requests you ran, with status codes, timings, and the responses received.' },
          { lead: 'Settings', text: 'Your preferences, such as theme, timeouts, and the diagnostics switch described below.' },
        ],
      },
      {
        title: 'B. Information Collected Automatically (Diagnostics)',
        intro: 'The App includes Firebase Analytics and Firebase Crashlytics. These are controlled by a Diagnostics switch in Settings, which is on by default and which you can turn off at any time. While it is on, these services may collect:',
        bullets: [
          { lead: 'Crash & Error Reports', text: 'Stack traces, app version, Android version, device model, and the app state at the time of a crash.' },
          { lead: 'Usage Analytics', text: 'Anonymous, aggregated information about how features are used, along with an app-instance identifier generated by Firebase.' },
        ],
      },
    ],
    outro: 'We do not intentionally collect or transmit the contents of your requests, responses, collections, or credentials to ourselves or to these services.',
  },
  {
    title: 'How Your Requests Are Sent',
    intro: 'When you run a request or open a WebSocket connection, the App sends it directly from your device to the server address you entered. The request does not pass through any STF Ecosystem server. We cannot see, store, or modify your requests or the responses you receive.',
    bullets: [
      { lead: 'You Control the Destination', text: 'The servers you contact, and what you send to them, are governed by those servers’ own privacy practices.' },
      { lead: 'Network Security', text: 'Requests to https:// addresses are encrypted in transit by TLS. The App will also send requests to plain http:// addresses if you enter them, and those are not encrypted.' },
    ],
  },
  {
    title: 'How Your Data Is Stored & Protected',
    bullets: [
      { lead: 'Local Storage', text: 'Collections and history are kept in the App’s private on-device database, which other apps cannot access under Android’s security model.' },
      { lead: 'No Android Cloud Backup', text: 'The App opts out of Android automatic backup, so its data is not copied to your Google account backups.' },
      { lead: 'No Selling of Data', text: 'We do not sell, rent, or trade your information. We do not use your content to train AI or machine learning models.' },
    ],
  },
  {
    title: 'Your Choices and Control',
    bullets: [
      { lead: 'Import & Export', text: 'You can import and export collections (including Postman and cURL formats) using Android’s system file picker. You choose where files are saved or read from.' },
      { lead: 'Delete Your Data', text: 'You can delete individual requests, collections, or history entries inside the App, or remove all local data by clearing the App’s storage or uninstalling it in Android Settings.' },
      { lead: 'Turn Off Diagnostics', text: 'Switch off Diagnostics in Settings to stop Firebase Analytics and Crashlytics collection.' },
    ],
  },
  {
    title: 'Device Permissions',
    intro: 'Yemini API Tester may request the following Android permissions:',
    bullets: [
      { lead: 'Internet (INTERNET) & Network State (ACCESS_NETWORK_STATE)', text: 'Required to send the requests you run and to detect whether a connection is available.' },
      { lead: 'Notifications (POST_NOTIFICATIONS)', text: 'Optional. Used to show notifications delivered through Firebase Cloud Messaging. You can decline or revoke this at any time in Android Settings.' },
    ],
    outro: 'The App does not request access to your contacts, location, camera, microphone, photos, or files. Files are only accessed when you pick them through the system file picker.',
  },
];

const thirdParties: PolicyThirdParty[] = [
  { name: 'Google Play Services', url: 'https://policies.google.com/privacy' },
  { name: 'Google Analytics for Firebase', url: 'https://firebase.google.com/policies/analytics' },
  { name: 'Firebase Crashlytics', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Firebase Cloud Messaging', url: 'https://firebase.google.com/support/privacy' },
];

export const ApiTesterAppPrivacyPage: React.FC = () => (
  <AppPrivacyDocument
    appName="Yemini API Tester"
    platform="Android"
    effectiveDate="October 4, 2026"
    thirdParties={thirdParties}
    sections={sections}
    summary={
      <>
        Yemini API Tester works <strong>without an account</strong>. Your requests, collections, history, and any credentials you enter are stored <strong>only on your device</strong>, and requests go straight from your device to the servers you choose, never through ours. The App uses Firebase Analytics and Crashlytics for anonymous diagnostics, which you can switch off in Settings. Questions? Contact <MailLink />.
      </>
    }
  />
);

export default ApiTesterAppPrivacyPage;
