import React from 'react';
import { AppPrivacyDocument, MailLink, PolicySection, PolicyThirdParty } from '../components/AppPrivacyDocument';

const sections: PolicySection[] = [
  {
    title: 'Information We Collect',
    subsections: [
      {
        title: 'A. Information That Stays on Your Device',
        intro: 'Yemini DBMS has no account system. The following is stored only on your device:',
        bullets: [
          { lead: 'Connection Profiles', text: 'Names, host addresses, ports, database names, and usernames for the database servers you add.' },
          { lead: 'Credentials', text: 'Database passwords, and SSH passwords or private keys if you use an SSH tunnel. Passwords are stored in an encrypted credential store backed by the Android Keystore.' },
          { lead: 'Queries & History', text: 'Saved SQL queries, query history, and the table and schema designs you create in the App.' },
          { lead: 'Settings & Logs', text: 'Your preferences and an in-app activity log used for troubleshooting on your device.' },
        ],
      },
      {
        title: 'B. Information Collected Automatically',
        intro: 'The App includes Firebase Analytics and Firebase Crashlytics, and Firebase App Check to confirm requests to Firebase come from a genuine copy of the App. These services may collect:',
        bullets: [
          { lead: 'Crash & Error Reports', text: 'Stack traces, app version, Android version, device model, and the app state at the time of a crash.' },
          { lead: 'Usage Analytics', text: 'Anonymous, aggregated information about how features are used, along with an app-instance identifier generated by Firebase.' },
        ],
      },
    ],
    outro: 'We do not intentionally collect or transmit your database contents, query results, connection details, or credentials to ourselves or to these services.',
  },
  {
    title: 'How Your Database Connections Work',
    intro: 'When you connect to a database, the App opens a connection directly from your device to the server address you entered, using PostgreSQL, MySQL, SQL Server, or SQLite drivers. If you enable an SSH tunnel, the App connects to your SSH host first and forwards the database traffic through it.',
    bullets: [
      { lead: 'No Relay Through Our Servers', text: 'Your queries and results never pass through any STF Ecosystem server. We cannot see them.' },
      { lead: 'You Control the Destination', text: 'The servers you connect to, and the data you read or change there, are governed by those servers’ operators and your own policies.' },
      { lead: 'Connection Security', text: 'Whether a connection is encrypted depends on how the database server and your connection settings are configured.' },
    ],
  },
  {
    title: 'How Your Data Is Protected',
    bullets: [
      { lead: 'Encrypted Credentials', text: 'Saved passwords are encrypted at rest using keys held in the Android Keystore.' },
      { lead: 'Biometric Lock', text: 'You can protect the App with your device’s fingerprint or face unlock. Authentication is performed entirely by Android. The App receives only a success or failure result and never has access to your biometric data.' },
      { lead: 'Screenshot Protection', text: 'The App blocks screenshots and hides its content in the recent-apps view, to reduce the chance of credentials or data being exposed.' },
      { lead: 'Encrypted Backups You Control', text: 'You can export your connections and history to a backup file. The file is encrypted with AES-256-GCM using a passphrase you choose. The passphrase is never stored, so we cannot recover it. If you lose it, the backup cannot be opened.' },
      { lead: 'Android Device Backup', text: 'If Android device backup is turned on for your phone, Android may include the App’s data in your backups according to your system settings.' },
      { lead: 'No Selling of Data', text: 'We do not sell, rent, or trade your information. We do not use your content to train AI or machine learning models.' },
    ],
  },
  {
    title: 'Your Choices and Control',
    bullets: [
      { lead: 'Delete Your Data', text: 'You can delete individual connections, queries, history, and designs inside the App, or remove all local data by clearing the App’s storage or uninstalling it in Android Settings.' },
      { lead: 'Notifications', text: 'You can decline or revoke the notification permission at any time in Android Settings.' },
    ],
  },
  {
    title: 'Optional Support Purchases',
    intro: 'Yemini DBMS offers optional one-time “support the developer” purchases through Google Play Billing, and links to external donation pages (Buy Me a Coffee and Ko-fi).',
    bullets: [
      { lead: 'Google Play Purchases', text: 'Payments are processed entirely by Google Play. We never see or store your card or payment details. Google may share purchase confirmation with the App so it can acknowledge your support.' },
      { lead: 'External Donation Pages', text: 'If you open a donation link, you leave the App and the site’s own privacy policy applies.' },
    ],
  },
  {
    title: 'Device Permissions',
    intro: 'Yemini DBMS may request the following Android permissions:',
    bullets: [
      { lead: 'Internet (INTERNET) & Network State (ACCESS_NETWORK_STATE)', text: 'Required to connect to your database servers and SSH hosts.' },
      { lead: 'Biometric (USE_BIOMETRIC)', text: 'Required only if you enable the biometric lock.' },
      { lead: 'Notifications (POST_NOTIFICATIONS)', text: 'Optional. Used to show notifications delivered through Firebase Cloud Messaging.' },
    ],
    outro: 'The App does not request access to your contacts, location, camera, or microphone. Files are only accessed when you pick them through the system file picker.',
  },
];

const thirdParties: PolicyThirdParty[] = [
  { name: 'Google Play Services & Google Play Billing', url: 'https://policies.google.com/privacy' },
  { name: 'Google Analytics for Firebase', url: 'https://firebase.google.com/policies/analytics' },
  { name: 'Firebase Crashlytics', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Firebase Cloud Messaging & App Check', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Buy Me a Coffee', url: 'https://www.buymeacoffee.com/privacy-policy' },
  { name: 'Ko-fi', url: 'https://more.ko-fi.com/privacy' },
];

export const DbmsAppPrivacyPage: React.FC = () => (
  <AppPrivacyDocument
    appName="Yemini DBMS"
    platform="Android"
    effectiveDate="October 4, 2026"
    thirdParties={thirdParties}
    sections={sections}
    summary={
      <>
        Yemini DBMS works <strong>without an account</strong>. Your connections, credentials, queries, and designs are stored <strong>only on your device</strong>, with passwords encrypted using the Android Keystore. The App connects <strong>directly</strong> from your device to your database servers, never through ours. It uses Firebase Analytics and Crashlytics for anonymous diagnostics. Questions? Contact <MailLink />.
      </>
    }
  />
);

export default DbmsAppPrivacyPage;
