import React from 'react';
import { AppPrivacyDocument, MailLink, SUPPORT_EMAIL, PolicySection, PolicyThirdParty } from '../components/AppPrivacyDocument';

const sections: PolicySection[] = [
  {
    title: 'Information We Collect',
    subsections: [
      {
        title: 'A. Your Photos and Videos Stay on Your Device',
        intro: 'You can use Yemini Image Editor without creating an account. Editing happens on your device:',
        bullets: [
          { lead: 'Photos & Videos', text: 'Media you open in the App is read from your device and processed locally. It is not uploaded to our servers.' },
          { lead: 'Projects & Presets', text: 'Your projects, edit history, presets, and settings are stored in the App’s private on-device database.' },
          { lead: 'On-Device Analysis', text: 'Features such as face retouching and subject cut-out use Google ML Kit models that run on your device. The images being analyzed are not sent to us. The models themselves may be downloaded to your device by Google Play services.' },
        ],
      },
      {
        title: 'B. If You Sign In (Optional)',
        intro: 'Signing in with Google is optional and is used for the template points feature. If you sign in, Firebase Authentication provides us with:',
        bullets: [
          { lead: 'Account Identifiers', text: 'Your Google account ID, display name, and email address, and a sign-in token used to confirm your identity to our server.' },
        ],
      },
      {
        title: 'C. If You Share a Design as a Template (Optional)',
        intro: 'The App lets you submit a design you made to be reviewed as a public template. If you choose to share one, we receive:',
        bullets: [
          { lead: 'The Design', text: 'Its text, shapes, emoji stickers, and hand drawing, plus the name, category, and description you provide. Your photos are never included.' },
          { lead: 'Identifiers', text: 'An anonymous ID generated for your installation of the App and, if you are signed in, your account ID. These are used to limit the number of designs waiting for review and to credit points to you.' },
        ],
      },
      {
        title: 'D. Information Collected Automatically',
        intro: 'The App includes Firebase Analytics and Firebase Crashlytics, and Firebase App Check to confirm requests to Firebase come from a genuine copy of the App. These services may collect:',
        bullets: [
          { lead: 'Crash & Error Reports', text: 'Stack traces, app version, Android version, device model, and the app state at the time of a crash.' },
          { lead: 'Usage Analytics', text: 'Anonymous, aggregated information about how features are used, along with an app-instance identifier generated by Firebase.' },
        ],
      },
    ],
  },
  {
    title: 'How We Use and Store Shared Templates',
    intro: 'A shared design is sent to our server (hosted on Cloudflare Workers) and stored in a database (hosted on Neon) as pending. It is not shown to anyone else until our team approves it.',
    bullets: [
      { lead: 'If Approved', text: 'The design becomes part of the public template list shown to all users of the App, and points are credited to you.' },
      { lead: 'If Rejected', text: 'It is not published. We may keep the submission record for moderation and abuse prevention.' },
      { lead: 'Templates You Download', text: 'When you open the Templates tab, the App downloads the template list and template photos from our server. As with any request, your IP address is visible to the servers that handle it.' },
    ],
  },
  {
    title: 'Fonts',
    intro: 'To offer additional fonts, the App may download font files from Google Fonts. Google receives your IP address and the font requested when this happens, and its own privacy policy applies.',
  },
  {
    title: 'Saving and Sharing Your Work',
    bullets: [
      { lead: 'Saving', text: 'Exported images and videos are saved to the Pictures/Yemini folder on your device.' },
      { lead: 'Metadata (EXIF)', text: 'The export screen lets you choose whether to preserve EXIF metadata. Photo metadata can include the date, camera model, and, if your camera recorded it, location. Turn this off before sharing if you do not want that information to travel with the file.' },
      { lead: 'Sharing', text: 'When you share an export, Android passes it to the app you choose, and that app’s privacy policy applies.' },
    ],
  },
  {
    title: 'How Your Data Is Protected',
    bullets: [
      { lead: 'Local Storage', text: 'On-device data is kept in the App’s private storage, which other apps cannot access under Android’s security model.' },
      { lead: 'Transit Encryption', text: 'Communication with our server and with Firebase uses HTTPS.' },
      { lead: 'No Selling of Data', text: 'We do not sell, rent, or trade your information. We do not use your photos, videos, or designs to train AI or machine learning models.' },
    ],
  },
  {
    title: 'Your Choices and Control',
    bullets: [
      { lead: 'Choose What the App Can See', text: 'On Android 14 and later you can grant access to selected photos and videos only.' },
      { lead: 'Delete Local Data', text: 'You can delete projects inside the App, or remove all local data by clearing the App’s storage or uninstalling it in Android Settings.' },
      { lead: 'Sign Out & Delete Your Account', text: (
        <>You can sign out at any time in Settings. To delete your account and the associated data held on our server, email <MailLink /> or use our <a href="#/delete-account" className="text-[#ba1724] dark:text-[#ff8585] underline">Account Deletion Request page</a>. You can also ask us to remove a design you submitted.</>
      ) },
    ],
  },
  {
    title: 'Device Permissions',
    intro: 'Yemini Image Editor may request the following Android permissions:',
    bullets: [
      { lead: 'Photos & Videos (READ_MEDIA_IMAGES, READ_MEDIA_VIDEO, READ_MEDIA_VISUAL_USER_SELECTED)', text: 'Required to open the photos and videos you want to edit. On older Android versions, the equivalent storage permission is used.' },
      { lead: 'Storage (WRITE_EXTERNAL_STORAGE, Android 9 and below only)', text: 'Required to save exported files to your Pictures folder on older Android versions.' },
      { lead: 'Internet (INTERNET)', text: 'Required for sign-in, downloading templates and fonts, sharing designs, and diagnostics.' },
      { lead: 'Notifications (POST_NOTIFICATIONS)', text: 'Optional. Used to show notifications delivered through Firebase Cloud Messaging.' },
    ],
  },
];

const thirdParties: PolicyThirdParty[] = [
  { name: 'Google Play Services & Google ML Kit', url: 'https://policies.google.com/privacy' },
  { name: 'Firebase Authentication & Google Sign-In', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Google Analytics for Firebase', url: 'https://firebase.google.com/policies/analytics' },
  { name: 'Firebase Crashlytics', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Firebase Cloud Messaging & App Check', url: 'https://firebase.google.com/support/privacy' },
  { name: 'Google Fonts', url: 'https://developers.google.com/fonts/faq/privacy' },
  { name: 'Cloudflare (template server)', url: 'https://www.cloudflare.com/privacypolicy/' },
  { name: 'Neon (template database)', url: 'https://neon.com/privacy-policy' },
];

export const ImageEditorAppPrivacyPage: React.FC = () => (
  <AppPrivacyDocument
    appName="Yemini Image Editor"
    platform="Android"
    effectiveDate="October 4, 2026"
    thirdParties={thirdParties}
    sections={sections}
    summary={
      <>
        Yemini Image Editor edits your photos and videos <strong>on your device</strong>, and they are never uploaded to us. You can use it <strong>without an account</strong>. If you choose to sign in with Google or share a design as a template, we receive the limited information described below. The App uses Firebase Analytics and Crashlytics for anonymous diagnostics. Questions? Contact <a href={`mailto:${SUPPORT_EMAIL}`} className="text-[#ba1724] dark:text-[#ff8585] underline font-mono">{SUPPORT_EMAIL}</a>.
      </>
    }
  />
);

export default ImageEditorAppPrivacyPage;
