import React, { useState } from 'react';
import { Sparkles, Terminal, CheckCircle2, ChevronRight, FileCode, Play, AlertCircle, RefreshCw, Send, Check, Layers } from 'lucide-react';

interface AgentStep {
  stepNumber: number;
  label: string;
  action: string;
  details: string;
  codeSnippet?: string;
  terminalLog?: string;
}

export const AiAgentInteractive: React.FC = () => {
  const [activeStepIndex, setActiveStepIndex] = useState(1);
  const [userPrompt, setUserPrompt] = useState('Add JWT authentication to the API router with token expiration.');
  const [isProcessing, setIsProcessing] = useState(false);

  const agentSteps: AgentStep[] = [
    {
      stepNumber: 1,
      label: 'AST Indexing',
      action: 'Inspecting project directory tree & dependencies',
      details: 'Scanned 14 source files in `/src`. Detected Express router in `routes/api.ts` and user models in `models/user.ts`. Identified missing jsonwebtoken dependency.',
      terminalLog: '$ yemini-ai index --ast /workspace\n✔ Indexed 14 files (3,412 AST nodes) in 18ms\n✔ Found target endpoint: POST /api/login in routes/api.ts'
    },
    {
      stepNumber: 2,
      label: 'Diff Generation',
      action: 'Constructing cryptographic diff for verification',
      details: 'Formulated `authMiddleware.ts` and attached claims verification to router without altering existing endpoints.',
      codeSnippet: `// + Generated by Yemini AI (STF Context Engine)
import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_SECRET || 'dev_secret_key';

export function authenticateToken(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];
  
  if (!token) return res.status(401).json({ error: 'Access token required' });
  
  jwt.verify(token, JWT_SECRET, (err, user) => {
    if (err) return res.status(403).json({ error: 'Invalid or expired token' });
    req.user = user;
    next();
  });
}`
    },
    {
      stepNumber: 3,
      label: 'Sandbox Tests',
      action: 'Executing test suite in isolated sandbox',
      details: 'Executed local test suite using native runner. 8 of 8 unit tests passed with 100% type coverage.',
      terminalLog: '$ npm test -- --grep "Authentication"\n PASS  tests/auth.test.ts (0.14s)\n  ✔ Reject unauthenticated requests with 401\n  ✔ Accept valid signed JWT tokens with 200 OK\n  ✔ Reject expired tokens with 403\n\nTest Suites: 1 passed, 1 total'
    },
    {
      stepNumber: 4,
      label: 'User Approval',
      action: 'Presenting structured summary for user confirmation',
      details: 'Ready to write 1 new file and modify 1 existing file. No breaking API changes detected.',
      terminalLog: 'Proposed Changes:\n + src/middleware/authMiddleware.ts (24 lines)\n ~ src/routes/api.ts (modified 4 lines)\n\n[Waiting for user approval: y/N]'
    }
  ];

  const handleSimulatePrompt = () => {
    setIsProcessing(true);
    setActiveStepIndex(0);
    
    setTimeout(() => {
      setActiveStepIndex(1);
    }, 400);

    setTimeout(() => {
      setActiveStepIndex(2);
      setIsProcessing(false);
    }, 800);
  };

  return (
    <div className="w-full max-w-4xl mx-auto bg-[#0c0c10] border border-zinc-800 rounded-2xl sm:rounded-3xl shadow-2xl overflow-hidden text-sm flex flex-col yemini-glow-hover">
      {/* Top Banner with Coming Soon Label */}
      <div className="px-4 sm:px-6 py-3 sm:py-4 bg-[#0e0e14] border-b border-zinc-800 flex flex-wrap items-center justify-between gap-2.5">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 sm:p-2 rounded-xl bg-gradient-to-br from-[#5b0000] to-[#ff6767] text-white shadow-md shrink-0">
            <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
          </div>
          <div>
            <div className="flex items-center gap-1.5 flex-wrap">
              <span className="font-bold text-white text-sm sm:text-base">Yemini AI Agent</span>
              <span className="text-[9px] sm:text-[10px] font-mono px-1.5 py-0.5 rounded-full bg-[#5b0000]/60 border border-[#ff6767]/40 text-[#ff8585]">
                Coming Soon
              </span>
            </div>
            <p className="text-[11px] sm:text-xs text-zinc-400">Autonomous codebase reasoning engine</p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 text-[10px] sm:text-xs text-zinc-400 font-mono">
          <span className="w-2 h-2 rounded-full bg-[#ff6767] animate-ping" />
          <span>Multi-turn reasoning</span>
        </div>
      </div>

      {/* Simulated User Prompt Bar */}
      <div className="p-3 sm:p-5 bg-[#09090c] border-b border-zinc-800/80 space-y-2">
        <div className="text-[10px] sm:text-xs font-mono uppercase tracking-wider text-zinc-400">
          User Intent Demonstration
        </div>
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 bg-[#121218] border border-zinc-700/80 rounded-2xl p-1.5 sm:p-2 sm:pl-3 shadow-inner">
          <input
            type="text"
            value={userPrompt}
            onChange={(e) => setUserPrompt(e.target.value)}
            className="flex-1 bg-transparent px-2 sm:px-0 text-zinc-100 text-xs sm:text-sm focus:outline-none"
            placeholder="Describe what you want the agent to build..."
          />
          <button
            onClick={handleSimulatePrompt}
            disabled={isProcessing}
            className="flex items-center justify-center gap-1.5 px-3 sm:px-4 py-2 rounded-xl bg-gradient-to-r from-[#5b0000] to-[#ff4d4d] hover:from-[#7a0000] hover:to-[#ff6767] text-white font-semibold text-xs transition-all active:scale-95 disabled:opacity-50 shrink-0"
          >
            {isProcessing ? <RefreshCw className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
            <span>Simulate Agent</span>
          </button>
        </div>
      </div>

      {/* Step Process Visualizer */}
      <div className="grid grid-cols-2 sm:grid-cols-4 border-b border-zinc-800/80 bg-[#0a0a0e]">
        {agentSteps.map((step, idx) => {
          const isCurrent = idx === activeStepIndex;
          const isDone = idx < activeStepIndex;
          return (
            <button
              key={step.stepNumber}
              onClick={() => setActiveStepIndex(idx)}
              className={`p-2.5 sm:p-3.5 text-left border-r border-b sm:border-b-0 border-zinc-800/80 transition-all ${
                isCurrent
                  ? 'bg-zinc-800/60 sm:border-b-2 sm:border-b-[#ff6767]'
                  : 'hover:bg-zinc-900/40 text-zinc-400'
              }`}
            >
              <div className="flex items-center gap-1.5">
                <span className={`w-4 h-4 sm:w-5 sm:h-5 rounded-full flex items-center justify-center text-[9px] sm:text-[10px] font-mono font-bold shrink-0 ${
                  isDone
                    ? 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                    : isCurrent
                    ? 'bg-[#5b0000] text-white border border-[#ff6767]'
                    : 'bg-zinc-900 text-zinc-500 border border-zinc-800'
                }`}>
                  {isDone ? '✓' : step.stepNumber}
                </span>
                <span className={`text-[11px] sm:text-xs font-semibold truncate ${isCurrent ? 'text-white' : 'text-zinc-400'}`}>
                  {step.label}
                </span>
              </div>
            </button>
          );
        })}
      </div>

      {/* Active Step Details & Code / Terminal Inspection */}
      <div className="p-3.5 sm:p-6 bg-[#070709] space-y-3.5">
        <div className="flex items-start gap-2.5">
          <div className="p-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-[#ff8585] shrink-0 mt-0.5">
            <Sparkles className="w-3.5 h-3.5" />
          </div>
          <div>
            <h4 className="text-xs sm:text-sm font-semibold text-white">
              {agentSteps[activeStepIndex].action}
            </h4>
            <p className="text-[11px] sm:text-xs text-zinc-400 mt-0.5 leading-relaxed">
              {agentSteps[activeStepIndex].details}
            </p>
          </div>
        </div>

        {/* Code Diff Display (if any) */}
        {agentSteps[activeStepIndex].codeSnippet && (
          <div className="rounded-xl sm:rounded-2xl border border-zinc-800 bg-[#0a0a0e] overflow-hidden">
            <div className="px-3 py-1.5 sm:px-4 sm:py-2 bg-[#0e0e14] border-b border-zinc-800 flex items-center justify-between text-[10px] sm:text-xs font-mono text-zinc-400 gap-2">
              <span className="flex items-center gap-1.5 text-emerald-400 truncate">
                <FileCode className="w-3 h-3 sm:w-3.5 sm:h-3.5 shrink-0" />
                <span className="truncate">authMiddleware.ts (New file proposed)</span>
              </span>
              <span className="text-[9px] text-zinc-500 font-sans shrink-0 hidden sm:inline">Strict Type Checking Passed</span>
            </div>
            <pre className="p-3 sm:p-4 text-[10.5px] sm:text-xs font-mono text-zinc-200 overflow-x-auto leading-relaxed">
              <code>{agentSteps[activeStepIndex].codeSnippet}</code>
            </pre>
          </div>
        )}

        {/* Terminal Execution Log (if any) */}
        {agentSteps[activeStepIndex].terminalLog && (
          <div className="rounded-xl sm:rounded-2xl border border-zinc-800 bg-[#09090c] p-3 sm:p-4 text-[10.5px] sm:text-xs font-mono">
            <div className="flex items-center gap-1.5 text-zinc-400 pb-1.5 mb-1.5 border-b border-zinc-800/80">
              <Terminal className="w-3.5 h-3.5 text-[#ff6767]" />
              <span className="font-semibold text-zinc-300 text-[10px] sm:text-xs">Yemini AI Sandboxed Terminal Execution</span>
            </div>
            <pre className="text-zinc-300 whitespace-pre-wrap leading-relaxed overflow-x-auto">
              {agentSteps[activeStepIndex].terminalLog}
            </pre>
          </div>
        )}
      </div>

      {/* Footer Guarantee */}
      <div className="px-4 sm:px-6 py-2.5 sm:py-3 bg-[#09090d] border-t border-zinc-800 flex flex-col sm:flex-row items-center justify-between gap-1 text-[10px] sm:text-xs text-zinc-500 font-mono text-center sm:text-left">
        <span>🔒 Zero Telemetry: Source code is never retained for training.</span>
        <span className="text-zinc-400">STF Responsible AI Standard</span>
      </div>
    </div>
  );
};
